#!/bin/bash
TRADEMARK="\xe2\x84\xa2"
echo -e "CleanDesktop${TRADEMARK}"

YYMMDD="`date '+%F'`"
SYSNAME="`uname -n`"
USERNAME="`echo ${HOME} | sed 's/\/home\///'`"
FILENAME="${YYMMDD}_${USERNAME}_${SYSNAME}_desktop_backup.tar.gz"


# check to see whether there are even files to archive
FILE_COUNT=`find $HOME/Desktop/* -maxdepth 0 -type f -not -name ".*" 2> /dev/null | wc -l`
DIRECTORY_COUNT=`find $HOME/Desktop/* -maxdepth 0 -type d -not -name ".*" 2> /dev/null | wc -l`

if [ $FILE_COUNT == 0 ] && [ $DIRECTORY_COUNT == 0 ]; then
  echo -e "Nothing was found on the desktop! Your desktop is already CLEAN${TRADEMARK}!!"
  echo -e "Exiting with Cleanliness${TRADEMARK}..."
  exit
else
  echo "CleanDesktop found some stuff on your desktop!! Yayy!!"
  echo "Files found: ${FILE_COUNT}."
  echo "Directories found: ${DIRECTORY_COUNT}."
  echo ""
fi

echo "Checking backup directory..."
# make sure there's a backup directory
if ! test -d $HOME/backup; then
  echo "Creating backup directory..."
  mkdir $HOME/backup
fi

echo "Creating desktop backup directory..."
# make sure there's a test backup directory
if ! test -d $HOME/backup/desktop; then
  echo "Creating desktop backup directory..."
  mkdir $HOME/backup/desktop
fi

#Check to see whether filename exists in ~/backup directory.
REPEAT=0
while test -f $HOME/backup/desktop/$FILENAME; do

	if [ ! $LETTER ]; then
	   LETTER="a"
  else

     DEC=`printf '%d' "'${LETTER}"`
	   if [ $DEC -ge 97 ] && [ $DEC -lt 103 ]; then
		    DEC=`expr ${DEC} + 1`
			  OCTAL=`expr ${DEC} + 44`
				LETTER=`echo -e "\0${OCTAL}"`
		 elif [ $DEC = 103 ]; then
		    LETTER="a"
			  REPEAT=`expr ${REPEAT} + 1`
		 fi
		 
  fi
	
	PRINT_LETTER="${LETTER}"
	REPEAT_THIS="${REPEAT}"
  while [ $REPEAT_THIS -gt 0 ]; do
	  PRINT_LETTER="${PRINT_LETTER}${LETTER}"
		REPEAT_THIS=`expr ${REPEAT_THIS} - 1`
	done

  FILENAME="${YYMMDD}${PRINT_LETTER}_${USERNAME}_${SYSNAME}_desktop_backup.tar.gz"
done


read -p "CleanDesktop will archive ${FILE_COUNT} files and ${DIRECTORY_COUNT} directories in \"${HOME}/backup/desktop/${FILENAME}\". Continue? (Y/n) " CONTINUE

while [ ! $CONTINUE == "yes" ] && [ ! $CONTINUE == "YES" ] && [ ! $CONTINUE == "Y" ] && [ ! $CONTINUE == "y" ] && [ ! $CONTINUE == "Yes" ]; do  
  
  if [ $CONTINUE == "no" ] || [ $CONTINUE == "NO" ] || [ $CONTINUE == "N" ] || [ $CONTINUE == "n" ] ||[ $CONTINUE == "NO" ]; then
    exit
  else
    read -p "I have no idea what you just said. Continue, or not? (Y/n) " CONTINUE
  fi

done


#Run tar command and create backup package
sudo tar --exclude=".*" -cvpf $HOME/backup/desktop/$FILENAME $HOME/Desktop/

if test -f $HOME/backup/desktop/$FILENAME; then
  if [ $FILE_COUNT -gt 0 ]; then
    echo "File #{$FILENAME} successfully created"
    echo "Removing archived files from desktop..."
    find $HOME/Desktop/* -maxdepth 0 -type f -not -name ".*" -exec echo {} \; -exec rm {} \;
  fi

  if [ $DIRECTORY_COUNT -gt 0 ]; then
    echo ""
    echo "Removing archived directories from desktop..."
    find $HOME/Desktop/* -maxdepth 0 -type d -not -name ".*" -exec echo {} \; -exec rm -rf {} \;
  fi
else
  echo "error: Archive failed to create for unknown reason. Maybe check permissions on ~/backups/desktop?"
  echo "Exiting without deleting files."
fi
